# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 10:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deltas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattice', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=40), size=60)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-ts',),
            },
        ),
    ]
