# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 21:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delta',
            name='lattice',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=40), size=60),
        ),
    ]
